FROM python:3.10-slim

WORKDIR /worker

# Install system dependencies for OpenCV
RUN apt-get update && apt-get install -y libgl1-mesa-glx libglib2.0-0 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install --default-timeout 3000 --retries 5 -r requirements.txt

COPY src ./src

CMD ["python", "-u", "src/workers/predict_worker.py"] 